[package]
name = "finickctl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
config = { path = "../libs/config" }
ipc = { path = "../libs/ipc" }
serde_json = "1.0.139"
strum = "0.27.1"

[[bin]]
name="finick"
path="src/main.rs"